services:
  blog-database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=jack
      - POSTGRES_PASSWORD=sqlisbest
    volumes:
      - ./postgresdata/data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 3001:8080
    container_name: dev-admin